//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialTemplate.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SocialTemplate.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        internal static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        internal static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        internal static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        internal static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        internal static string OneSecondAgo {
            get {
                return ResourceManager.GetString("OneSecondAgo", resourceCulture);
            }
        }
        
        internal static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        internal static string AMinuteAgo {
            get {
                return ResourceManager.GetString("AMinuteAgo", resourceCulture);
            }
        }
        
        internal static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        internal static string AnHourAgo {
            get {
                return ResourceManager.GetString("AnHourAgo", resourceCulture);
            }
        }
        
        internal static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        internal static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        internal static string OneMonthAgo {
            get {
                return ResourceManager.GetString("OneMonthAgo", resourceCulture);
            }
        }
        
        internal static string MonthsAgo {
            get {
                return ResourceManager.GetString("MonthsAgo", resourceCulture);
            }
        }
        
        internal static string OneYearAgo {
            get {
                return ResourceManager.GetString("OneYearAgo", resourceCulture);
            }
        }
        
        internal static string YearsAgo {
            get {
                return ResourceManager.GetString("YearsAgo", resourceCulture);
            }
        }
        
        internal static string Joined {
            get {
                return ResourceManager.GetString("Joined", resourceCulture);
            }
        }
        
        internal static string WelcomeLogIn {
            get {
                return ResourceManager.GetString("WelcomeLogIn", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        internal static string LogInWithFacebook {
            get {
                return ResourceManager.GetString("LogInWithFacebook", resourceCulture);
            }
        }
        
        internal static string LogInWithGoogle {
            get {
                return ResourceManager.GetString("LogInWithGoogle", resourceCulture);
            }
        }
        
        internal static string HelloSignUp {
            get {
                return ResourceManager.GetString("HelloSignUp", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string ByClickingSignUp {
            get {
                return ResourceManager.GetString("ByClickingSignUp", resourceCulture);
            }
        }
        
        internal static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        internal static string ResetMyPassword {
            get {
                return ResourceManager.GetString("ResetMyPassword", resourceCulture);
            }
        }
        
        internal static string PleaseTypeYourEmail {
            get {
                return ResourceManager.GetString("PleaseTypeYourEmail", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        internal static string EditPhotoTapped {
            get {
                return ResourceManager.GetString("EditPhotoTapped", resourceCulture);
            }
        }
        
        internal static string EditCoverTapped {
            get {
                return ResourceManager.GetString("EditCoverTapped", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string RecentContact {
            get {
                return ResourceManager.GetString("RecentContact", resourceCulture);
            }
        }
        
        internal static string TypeYourMessage {
            get {
                return ResourceManager.GetString("TypeYourMessage", resourceCulture);
            }
        }
        
        internal static string ShareThe {
            get {
                return ResourceManager.GetString("ShareThe", resourceCulture);
            }
        }
        
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        internal static string YourReview {
            get {
                return ResourceManager.GetString("YourReview", resourceCulture);
            }
        }
        
        internal static string PostDetail {
            get {
                return ResourceManager.GetString("PostDetail", resourceCulture);
            }
        }
        
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        internal static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
    }
}
