using SocialTemplate.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace SocialTemplate.DataStores.MockDataStore
{
    /// <summary>
    /// Mock data store with fake entities to test.
    /// </summary>
    public class PersonDataStore : BaseDataStore<Person>, IPersonDataStore
    {
        protected override IList<Person> items { get; }

        public PersonDataStore()
        {
            items = new List<Person>()
            {
                new Person {
                  Id = "001",
                  Cover = "cover060",
                  Photo = "per_aenean_viverra",
                  FullName = "Aenean Viverra",
                  Username = "@aviverra",
                  Email = "aviverra@gmail.com",
                  Phone = "437 541 89 65",
                  Ticked = true,
                  Follower = false,
                  Following = false,
                  MemberDate = new DateTime(2018, 3, 8),
                  PostCount = 356,
                  FollowerCount = 190,
                  FollowingCount = 874,
                },
                new Person {
                  Id = "002",
                  Cover = "cover059",
                  Photo = "per_aliquam_posuere",
                  FullName = "Aliquam Posuere",
                  Username = "@aposuere",
                  Email = "aposuere@gmail.com",
                  Phone = "652 375 83 38",
                  Ticked = true,
                  Follower = true,
                  Following = false,
                  MemberDate = new DateTime(2018, 8, 12),
                  PostCount = 613,
                  FollowerCount = 181,
                  FollowingCount = 549
                },
                new Person {
                  Id = "003",
                  Cover = "cover058",
                  Photo = "per_arcu_sem",
                  FullName = "Arcu Sem",
                  Username = "@asem",
                  Email = "asem@gmail.com",
                  Phone = "239 873 63 11",
                  Ticked = true,
                  Follower = false,
                  Following = true,
                  MemberDate = new DateTime(2018, 1, 28),
                  PostCount = 815,
                  FollowerCount = 401,
                  FollowingCount = 207
                },
                new Person {
                  Id = "004",
                  Cover = "cover057",
                  Photo = "per_bibendum_potenti",
                  FullName = "Bibendum Potenti",
                  Username = "@bpotenti",
                  Email = "bpotenti@gmail.com",
                  Phone = "736 573 89 76",
                  Ticked = false,
                  Follower = false,
                  Following = false,
                  MemberDate = new DateTime(2018, 11, 8),
                  PostCount = 256,
                  FollowerCount = 851,
                  FollowingCount = 297
                },
                new Person {
                  Id = "005",
                  Cover = "cover056",
                  Photo = "per_dictum_vel",
                  FullName = "Dictum Vel",
                  Username = "@dvel",
                  Email = "dvel@gmail.com",
                  Phone = "541 353 76 33",
                  Ticked = false,
                  Follower = true,
                  Following = false,
                  MemberDate = new DateTime(2019, 11, 30),
                  PostCount = 937,
                  FollowerCount = 231,
                  FollowingCount = 454
                },
                new Person {
                  Id = "006",
                  Cover = "cover055",
                  Photo = "per_donec_ipsum",
                  FullName = "Donec Ipsum",
                  Username = "@dipsum",
                  Email = "dipsum@gmail.com",
                  Phone = "762 992 09 12",
                  Ticked = true,
                  Follower = false,
                  Following = true,
                  MemberDate = new DateTime(2019, 5, 20),
                  PostCount = 327,
                  FollowerCount = 830,
                  FollowingCount = 918
                },
                new Person {
                  Id = "007",
                  Cover = "cover054",
                  Photo = "per_dui_eu",
                  FullName = "Dui Eu",
                  Username = "@deu",
                  Email = "deu@gmail.com",
                  Phone = "761 98 35 33",
                  Ticked = false,
                  Follower = false,
                  Following = false,
                  MemberDate = new DateTime(2019, 3, 9),
                  PostCount = 148,
                  FollowerCount = 511,
                  FollowingCount = 296
                },
                new Person {
                  Id = "008",
                  Cover = "cover054",
                  Photo = "per_dui_molestie",
                  FullName = "Dui Molestie",
                  Username = "@dmolestie",
                  Email = "dmolestie@gmail.com",
                  Phone = "120 762 16 77",
                  Ticked = true,
                  Follower = true,
                  Following = false,
                  MemberDate = new DateTime(2019, 8, 11),
                  PostCount = 472,
                  FollowerCount = 246,
                  FollowingCount = 380
                },
                new Person {
                  Id = "009",
                  Cover = "cover053",
                  Photo = "per_efficitur_etiam",
                  FullName = "Efficitur Etiam",
                  Username = "@eetiam",
                  Email = "eetiam@gmail.com",
                  Phone = "341 452 53 99",
                  Ticked = true,
                  Follower = false,
                  Following = true,
                  MemberDate = new DateTime(2020, 10, 1),
                  PostCount = 103,
                  FollowerCount = 359,
                  FollowingCount = 745
                },
                new Person {
                  Id = "010",
                  Cover = "cover052",
                  Photo = "per_eget_eros",
                  FullName = "Eget Eros",
                  Username = "@eeros",
                  Email = "eeros@gmail.com",
                  Phone = "534 784 22 71",
                  Ticked = false,
                  Follower = false,
                  Following = false,
                  MemberDate = new DateTime(2020, 6, 29),
                  PostCount = 414,
                  FollowerCount = 297,
                  FollowingCount = 501
                },
                new Person {
                  Id = "011",
                  Cover = "cover051",
                  Photo = "per_eget_tortor",
                  FullName = "Eget Tortor",
                  Username = "@etortor",
                  Email = "etortor@gmail.com",
                  Phone = "762 362 90 12",
                  Ticked = false,
                  Follower = true,
                  Following = true,
                  MemberDate = new DateTime(2020, 7, 19),
                  PostCount = 968,
                  FollowerCount = 383,
                  FollowingCount = 108
                },
                new Person {
                  Id = "012",
                  Cover = "cover050",
                  Photo = "per_eget_varius",
                  FullName = "Eget Varius",
                  Username = "@evarius",
                  Email = "evarius@gmail.com",
                  Phone = "766 263 18 37",
                  Ticked = true,
                  Follower = false,
                  Following = false,
                  MemberDate = new DateTime(2020, 4, 10),
                  PostCount = 618,
                  FollowerCount = 293,
                  FollowingCount = 195
                },
                new Person {
                  Id = "013",
                  Cover = "cover049",
                  Photo = "per_erat_commodo",
                  FullName = "Erat Commodo",
                  Username = "@ecommodo",
                  Email = "ecommodo@gmail.com",
                  Phone = "766 172 21 09",
                  Ticked = false,
                  Follower = false,
                  Following = false,
                  MemberDate = new DateTime(2021, 10, 30),
                  PostCount = 605,
                  FollowerCount = 127,
                  FollowingCount = 397
                },
                new Person {
                  Id = "014",
                  Cover = "cover048",
                  Photo = "per_etiam_urna",
                  FullName = "Etiam Urna",
                  Username = "@eurna",
                  Email = "eurna@gmail.com",
                  Phone = "142 464 17 58",
                  Ticked = true,
                  Follower = true,
                  Following = true,
                  MemberDate = new DateTime(2021, 4, 19),
                  PostCount = 719,
                  FollowerCount = 615,
                  FollowingCount = 803
                },
                new Person {
                  Id = "015",
                  Cover = "cover047",
                  Photo = "per_facilisi_adipiscing",
                  FullName = "Facilisi Adipiscing",
                  Username = "@fadipiscing",
                  Email = "fadipiscing@gmail.com",
                  Phone = "987 887 61 81",
                  Ticked = false,
                  Follower = false,
                  Following = false,
                  MemberDate = new DateTime(2022, 5, 23),
                  PostCount = 910,
                  FollowerCount = 530,
                  FollowingCount = 261
                },
                new Person {
                  Id = "016",
                  Cover = "cover046",
                  Photo = "per_felis_urna",
                  FullName = "Felis Urna",
                  Username = "@furna",
                  Email = "furna@gmail.com",
                  Phone = "243 163 12 09",
                  Ticked = true,
                  Follower = false,
                  Following = true,
                  MemberDate = new DateTime(2022, 8, 5),
                  PostCount = 290,
                  FollowerCount = 401,
                  FollowingCount = 647
                },
            };
        }
    }
}
